version: '3.8'
services:
  client:
    build:
      context: ./client  # The path to your client Dockerfile and code
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      server: 
        condition: service_healthy

  server:
    build:
      context: ./server  # Updated path to the server Dockerfile and code
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/HealthCareDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"