version: '3.8'
services:
  server:
    build:
      context: ./server
    image: wad2-server:1.0
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/HealthCareDB
      NODE_OPTIONS: '--trace-warnings'
    depends_on:
      - mongo
    # healthcheck:
    #   test: curl --fail http://localhost:3500 || exit 1 
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    dns: 
      - 8.8.8.8

  client:
    build:
      context: ./client
    image: wad2-client:1.0
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"] 
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # sudo systemctl stop apache2

  # nginx:
  #   build:
  #     context: ./config
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - server
  #     - client
      