version: '3.8'
services:
  server:
    build:
      context: ./server
    image: wad2-server:1.0
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/HealthCareDB
      NODE_OPTIONS: '--trace-warnings'
    depends_on:
      - mongo
    dns: 
      - 8.8.8.8

  client:
    build:
      context: ./client
    image: wad2-client:1.0
    ports:
      # - "3000:3000"
      - "5173:5173"
    environment:
      NODE_ENV: production
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27017:27017"