version: '3.8'
services:
  backend:
    image: wad2-backend:1.0-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      MONGO_URI: mongodb://mongo:27017/HealthCareDB
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
