version: '3.8'
services:
  server:
    build:
      context: ../../server
    image: wad2-server:server-latest
    ports:
      - "3500:3500"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3500/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 5 
    dns: 
      - 8.8.8.8

  client:
    build:
      context: ../../client
    image: wad2-client:client-latest
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - VITE_DEVELOPMENT_SERVER=$VITE_DEVELOPMENT_SERVER
      - VITE_GITHUB_CLIENT_ID=$VITE_GITHUB_CLIENT_ID
      - VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
      - VITE_HTTPS_SERVER=$VITE_HTTPS_SERVER
      - VITE_NODE_ENV=$VITE_NODE_EN
    # volumes:
    #   - ./client:/client-docker/src
    # command: npm run dev

  nginx:
    image: wad2-nginx:nginx-latest
    restart: always
    build:
      context: ../../config
      dockerfile: Dockerfile
    ports:
      - 80:80
      # - 443:443
    depends_on:
      server:
        condition: service_healthy
      client:
        condition: service_started

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://localhost:27017/test", "--quiet", "--eval", "print(db.runCommand({ ping: 1 }).ok)"]
      interval: 5s
      timeout: 5s
      retries: 10
    # sudo systemctl stop apache2


      