name: Deploy Client to Heroku

on:
  push:
    branches:
      - main  
    paths:
      - 'client/**'

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build, Push and release Docker Image to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }}
        dockerfile_directory: ./client
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web

    # - name: Login to Heroku Container Registry
    #   run: heroku container:login
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # - name: Change working directory
    #   run: cd client

    # - name: Build and push client Docker image
    #   run: |
    #     heroku container:push web -a ${{ secrets.HEROKU_CLIENT_APP_NAME }}
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # - name: Release Client
    #   run: |
    #     heroku container:release web -a ${{ secrets.HEROKU_CLIENT_APP_NAME }}
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
