name: Deploy Client to Heroku

on:
  push:
    branches:
      - main  
    paths:
      - 'client/**'

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Heroku Container Registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push client Docker image
      run: |
        heroku container:push web --context-path ./client -a ${{ secrets.HEROKU_CLIENT_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release Client
      run: |
        heroku container:release web -a ${{ secrets.HEROKU_CLIENT_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
