# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Server to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Heroku Container Registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Change working directory to server
      run: cd server

    - name: Build and push server Docker image
      run: |
        heroku container:push web -a ${{ secrets.HEROKU_SERVER_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release Server
      run: heroku container:release web -a ${{ secrets.HEROKU_SERVER_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
