# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  EDAMAM_NUTRITION_API_KEY: ${{ secrets.EDAMAM_NUTRITION_API_KEY }}
  EDAMAM_NUTRITION_APP_ID: ${{ secrets.EDAMAM_NUTRITION_APP_ID }}
  EDAMAM_RECIPE_API_KEY: ${{ secrets.EDAMAM_RECIPE_API_KEY }}
  EDAMAM_RECIPE_APP_ID: ${{ secrets.EDAMAM_RECIPE_APP_ID }}
  GIT_CLIENT_ID: ${{ secrets.GIT_CLIENT_ID }}
  GIT_CLIENT_SECRET: ${{ secrets.GIT_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
  MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
  OTP_SECRET: ${{ secrets.OTP_SECRET }}
  TRANSPORTER_GMAIL: ${{ secrets.TRANSPORTER_GMAIL }}
  TRANSPORTER_PASSWORD: ${{ secrets.TRANSPORTER_PASSWORD }}
  VITE_DEVELOPMENT_SERVER: ${{ secrets.VITE_DEVELOPMENT_SERVER }}
  VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
  VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
  VITE_HTTPS_SERVER: ${{ secrets.VITE_HTTPS_SERVER }}
  VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install dependencies and run tests for the client application
      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          export VITE_DEVELOPMENT_SERVER=$VITE_DEVELOPMENT_SERVER
          export VITE_GITHUB_CLIENT_ID=$VITE_GITHUB_CLIENT_ID
          export VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
          export VITE_HTTPS_SERVER=$VITE_HTTPS_SERVER
          export VITE_NODE_ENV=$VITE_NODE_ENV
          npm run test
          
      # Install dependencies and run tests for the server application
      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          export DATABASE_URL=$DATABASE_URL
          export EDAMAM_NUTRITION_API_KEY=$EDAMAM_NUTRITION_API_KEY
          export EDAMAM_NUTRITION_APP_ID=$EDAMAM_NUTRITION_APP_ID
          export EDAMAM_RECIPE_API_KEY=$EDAMAM_RECIPE_API_KEY
          export EDAMAM_RECIPE_APP_ID=$EDAMAM_RECIPE_APP_ID
          export GIT_CLIENT_ID=$GIT_CLIENT_ID
          export GIT_CLIENT_SECRET=$GIT_CLIENT_SECRET
          export GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
          export GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
          export JWT_RESET_SECRET=$JWT_RESET_SECRET
          export MY_SECRET_KEY=$MY_SECRET_KEY
          export OTP_SECRET=$OTP_SECRET
          export TRANSPORTER_GMAIL=$TRANSPORTER_GMAIL
          export TRANSPORTER_PASSWORD=$TRANSPORTER_PASSWORD
          npm run test

      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wad2-client:client-${{github.run_number}}
            
      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wad2-server:server-${{github.run_number}}
            
      - name: Build and Push Nginx Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./config
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wad2-nginx:nginx-${{github.run_number}}
            ${{ secrets.DOCKER_USERNAME }}/wad2-nginx:nginx-latest

      # Authenticate with AWS ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-1 # Updated with your ECR region

      # Build a Docker image for the client application and push to ECR
      - name: Build and Push Client Docker Image
        id: build-client-image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: 030820224983.dkr.ecr.ap-southeast-1.amazonaws.com/healthcareapp:client-${{github.run_number}}

      # Build a Docker image for the server application and push to ECR
      - name: Build and Push Server Docker Image
        id: build-server-image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: 030820224983.dkr.ecr.ap-southeast-1.amazonaws.com/healthcareapp:server-${{github.run_number}}

      # Build a Docker image for the NGINX reverse proxy and push to ECR
      - name: Build and Push NGINX Docker Image
        id: build-nginx-image
        uses: docker/build-push-action@v2
        with:
          context: ./config
          push: true
          tags: 030820224983.dkr.ecr.ap-southeast-1.amazonaws.com/healthcareapp:nginx-${{github.run_number}};030820224983.dkr.ecr.ap-southeast-1.amazonaws.com/healthcareapp:nginx-latest
